name: build and test react app

on: push

jobs:
  build-app:
    name: build
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
